name = "debtcompassfinancial"
main = "worker.js"
compatibility_date = "2026-04-01"

[assets]
directory = "."

[[send_email]]
name = "ROSS_EMAIL"
destination_address = "rkrai3122@gmail.com"

[observability.logs]
enabled = true
invocation_logs = true